In [44]:
import cv2
import os
import numpy as np
import random
import time

class reader:
    def __init__(self, dir_name, batch_size, resize):
        self.dir_name = dir_name
        self.batch_size = batch_size
        #file list
        self.file_list = os.listdir(self.dir_name)
        #total batch num
        self.leng = len(self.file_list)
        self.total_batch = self.leng // self.batch_size
        #index
        #self.index = np.arange(1,self.leng + 1)
        
    
    def getList(self):
        return self.file_list
    
    def getTotalNum(self):
        return len(self.file_list)
    
    def next_batch(self):
        #image random choice
        np.random.shuffle(self.file_list)
        
        #init
        #file_name = np.array([self.file_list[:self.batch_size]])
        
        #index batch
        #file_name = np.reshape(self.file_list[:self.total_batch*self.batch_size],(-1,self.batch_size))
        
        batch = []
        
        start = time.time()
        #6331번
        for file_name in self.file_list:
                dir_n = self.dir_name + file_name
                img = cv2.imread(dir_n)
                batch.append(img)
                return np.array(batch).shape
        
        end = time.time()
        
        print(start-end)
        
        return batch.shape

In [45]:
r = reader('C:/Users/JM/Git_store/celebA/',32,1)

print(r.file_list[-1])
print(r.total_batch*32)
batch_xs = r.next_batch()
print(batch_xs)
#batch_xs = batch_xs * (2.0 / 255.0) - 1

202599.jpg
202592
(1, 218, 178, 3)


In [126]:
a = np.arange(1,6331)[:32]
print(len(a))

32


In [119]:
a = np.array([[0,1,2]])
a = np.append(a,[[1,2,3]],axis=0)

print(a)

[[0 1 2]
 [1 2 3]]


In [51]:
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.reshape(b[:-1],(-1,2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a = np.array(['000001.jpg','000002.jpg','000003.jpg','000004.jpg','000005.jpg'])

dir_n = 'C:/Users/JM/Git_store/celebA/'

print(a)

In [ ]:
(5, 218, 178, 3)


for i,name in enumerate(a):
    file = dir_n + name
    img = cv2.imread(file)
    a[i] = img